on: push
jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v0"

      - name: Docker を構成する
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build tag name
        env:
          TZ: "Asia/Tokyo"
        run: |
          TIME=$(date +'%Y%m%d%H%M%S')
          echo "TAG=${TIME}_${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build image
        run: docker build -t ${{ secrets.IMAGE_NAME }}:${{ env.TAG }} ./

      - name: Push image
        run: |
          docker push ${{ secrets.IMAGE_NAME}}:${{ env.TAG }}

      - name: Deploy Cloud Run
        run: |
          gcloud run deploy app \
            --image=${{ secrets.IMAGE_NAME }}:${{ env.TAG }} \
            --region=asia-northeast1 \
            --allow-unauthenticated \
            --revision-suffix=dt${{ env.TAG }}
